apiVersion: batch/v1
kind: CronJob
metadata:
  name: archive-logs
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: archive
            image: appropriate/curl
            command:
              - sh
              - -c
              - |
                TIMESTAMP=$(date +%s)
                curl -s http://custom-app-service/logs -o /tmp/app.log
                tar -czf /tmp/app-logs-${TIMESTAMP}.tar.gz -C /tmp app.log
                ls -lh /tmp
            resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "500m"
          restartPolicy: OnFailure
