apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-agent
  labels:
    app: log-agent
spec:
  selector:
    matchLabels:
      app: log-agent
  template:
    metadata:
      labels:
        app: log-agent
    spec:
      containers:
      - name: log-agent
        image: busybox
        command: [ "sh", "-c", "tail -F /app/logs/app.log" ]
        volumeMounts:
          - name: logs-volume
            mountPath: /app/logs
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
        - name: logs-volume
          hostPath:
            path: /var/log/myapp
            type: DirectoryOrCreate